export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const GET_GOALS_BEGIN = 'GET_GOALS_BEGIN'
export const GET_GOALS_SUCCESS = 'GET_GOALS_SUCCESS'

export const SET_EDIT_GOAL = 'SET_EDIT_GOAL'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_GOAL_BEGIN = 'CREATE_GOAL_BEGIN'
export const CREATE_GOAL_SUCCESS = 'CREATE_GOAL_SUCCESS'
export const CREATE_GOAL_ERROR = 'CREATE_GOAL_ERROR'

export const EDIT_GOAL_BEGIN = 'EDIT_GOAL_BEGIN'
export const EDIT_GOAL_SUCCESS = 'EDIT_GOAL_SUCCESS'
export const EDIT_GOAL_ERROR = 'EDIT_GOAL_ERROR'

export const DELETE_GOAL_BEGIN = 'DELETE_GOAL_BEGIN'

export const UPDATE_USER_BEGIN='UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const CLEAR_FILTER = 'CLEAR_FILTER'
export const CHANGE_PAGE = 'CHANGE_PAGE'